apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-app
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
    - port: 3000           # Service port
      targetPort: 3000     # Container port
      nodePort: 30080      # Exposed port on your machine (range: 30000–32767)
